### PR TITLE
allow using pymongo 4.3

### PR DESCRIPTION
**Pull request by mattotodd**
Upgrade dependecies requirements to support PyMongo 4+

### CODE REVIEW

**Comment by jefersondaniel** [comment]
Thanks!

**Comment by mattotodd** [comment]
@jefersondaniel do you have the ability to publish this to pypi?

**Comment by jefersondaniel** [comment]
@mattotodd It's available as 1.0.0 now. I was doing some changes on the github actions but now its ready.

**Comment by mattotodd** [comment]
awesome, thx

**Pull request merged**
