### PR TITLE
Fixes, AsyncAbstractRepository and more

### PR DESCRIPTION
**Pull request by Artucuno**
- Add `delete_many()` (7a82aae14aa488b71e639c8819d6d7bb90edb035)
- Update `save_many()` (7a82aae14aa488b71e639c8819d6d7bb90edb035)
- Update type hints (7dbd970fdd84fb70613ade50ec455b2d60645f7a)
- Add document_count property. (7a82aae14aa488b71e639c8819d6d7bb90edb035)
- Update a few functions listed in #42 (586e06d7e1a2a3ec1d9c4827d4e51e34364a7316)
- Fixes for #48 (`pydantic.errors.PydanticInvalidForJsonSchema`) (7ea504864fceb1fcaafba5a06687fa3875c6984b)
- Add `paginate_simple()` method (1abbf930dbd368d25d7d77b83877eecc81d53194)
- Add `AsyncAbstractRepository` class (4ca7bd942891cc10f1135b70de20dc8d4a3be819)
  - Interact with MongoDB using Asynchronous calls
- Update `to_document` staticmethod to dump models in "JSON mode" (5de2c5cbfc8e5465e560cc61424d8d63ba148758)
  - This makes the dictionary only contain JSON serializable types and fixes types like Enums, etc.

### CODE REVIEW

**Comment by Artucuno** [comment]
Just noticed that my IDE indented a bunch of stuff for no reason. It doesn't seem to interfere with anything but I can fix it if needed.

**Comment by Artucuno** [comment]
Also fixed the weird indents from [7a82aae](https://github.com/jefersondaniel/pydantic-mongo/pull/45/commits/7a82aae14aa488b71e639c8819d6d7bb90edb035)

**Comment by Artucuno** [comment]
7ea504864fceb1fcaafba5a06687fa3875c6984b validated with:

<details>
  <summary>Click me</summary>

```py
from bson import ObjectId
from fastapi import FastAPI
from icecream import ic
from pydantic import BaseModel

from pydantic_mongo import ObjectIdField


class Foo(BaseModel):
    id: ObjectIdField = None
    message: str


app = FastAPI()


@app.get("/", response_model=Foo)
async def root():
    return {"id": ObjectId(), "message": "Hello World"}


bar = Foo(id=ObjectId(), message="Hello World")

md = bar.model_dump()
ic(md)
ic(type(Foo.model_validate(md).id))

mdj = bar.model_dump_json()
ic(mdj)
ic(type(Foo.model_validate_json(mdj).id))

if __name__ == '__main__':
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
```
</details>

Results with:
```py
ic| md: {'id': '6567d22651631f1e5982e518', 'message': 'Hello World'}
ic| type(Foo.model_validate(md).id): <class 'bson.objectid.ObjectId'>
ic| mdj: '{"id":"6567d22651631f1e5982e518","message":"Hello World"}'
ic| type(Foo.model_validate_json(mdj).id): <class 'bson.objectid.ObjectId'>
```
while maintaining OpenAPI compatibility
image

**Comment by jefersondaniel** [comment]
Thanks @Artucuno,

I'm not sure about the best implementation for kwargs, I want to keep type hints whenever possible, what do you think about the typehints for kwargs?

You can send kwargs as a separate PR so I can merge the other changes first

**Comment by Artucuno** [comment]
> I'm not sure about the best implementation for kwargs, I want to keep type hints whenever possible. What do you think about the typehints for kwargs?

Sorry for the late response. What do you mean about typehints for kwargs? Since the kwargs are being passed directly to pymongo, I don't think that it would need typehinting.

**Comment by Artucuno** [comment]
Temporarily converted this to a draft to fix some things

**Comment by Artucuno** [comment]
I don't think that the README or Linting tests are necessary. The linting should be a Github action instead, but its also broken.

image
 
image

**Comment by Artucuno** [comment]
Omg finally

**Comment by Artucuno** [comment]
@jefersondaniel Is there anything else that you need me to do?

Thanks,
Artu

**Comment by jefersondaniel** [comment]
Hi @Artucuno,

Thank you for the effort and time you've put into this PR.  appreciate some of the ideas you've introduced, such as delete_many and AsyncAbstractRepository. These are great additions.

However, I have some concerns about the scope of this PR. I generally prefer to work with single-purpose PRs as they're easier to review, test, and discuss.

I also have some reservations about the extensive use of kwargs in some of the changes. While kwargs can offer flexibility, their overuse might compromise the code's maintainability. This approach increases coupling with implementation details, as callers need to have a understanding of how the function is implemented and where the kwargs are being utilized.

I'm closing this PR for now, but I want to incorporate some of your changes. If you have any further thoughts or decide to submit smaller PRs in the future, I would be more than happy to review them. Otherwise I'll review this code more carefully and try to cherry-pick some of the changes.

**Pull request closed without merging**
